export type PrintableQuestion = {
  text: string;
  options: string[];
  answerIdx: number;
  difficulty: number;
  topicName: string;
};

export function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

const BASE_STYLES = `
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; padding: 40px; color: #0F172A; }
  .header { border-bottom: 2px solid #2563EB; padding-bottom: 12px; margin-bottom: 24px; display: flex; justify-content: space-between; gap: 16px; }
  h1 { margin: 0; color: #2563EB; font-size: 22px; }
  .meta { font-size: 13px; color: #64748B; margin-top: 4px; }
  .section { margin-bottom: 28px; }
  .section-title { font-size: 15px; font-weight: bold; background: #EFF6FF; padding: 8px 12px; border-radius: 6px; margin-bottom: 12px; }
  .question { margin-bottom: 18px; font-size: 14px; line-height: 1.6; page-break-inside: avoid; }
  .options { display: grid; grid-template-columns: 1fr 1fr; gap: 4px 16px; margin: 6px 0 0 20px; color: #334155; }
  .workspace { border: 1px dashed #CBD5E1; height: 70px; border-radius: 8px; margin-top: 8px; }
  .badge { display: inline-block; padding: 1px 8px; border-radius: 12px; font-size: 11px; font-weight: bold; background: #EFF6FF; color: #1D4ED8; margin-left: 6px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th, td { text-align: left; padding: 6px 8px; border-bottom: 1px solid #E2E8F0; }
  th { color: #64748B; }
  .answer-key { page-break-before: always; }
  .footer { margin-top: 40px; border-top: 1px solid #E2E8F0; padding-top: 12px; font-size: 12px; color: #94A3B8; text-align: center; }
  @media print { .no-print { display: none; } }
`;

/**
 * Opens a blank tab synchronously (must run inside the click handler so pop-up blockers allow it).
 * Returns a writer to fill it in later, e.g. after an async fetch.
 */
export function openPrintWindow(): ((title: string, bodyHtml: string) => void) | null {
  const win = window.open("", "_blank");
  if (!win) return null;
  win.document.write("<p style='font-family:sans-serif;padding:40px'>Preparing…</p>");
  return (title, bodyHtml) => {
    win.document.open();
    win.document.write(`<!DOCTYPE html>
<html>
  <head><meta charset="utf-8" /><title>${escapeHtml(title)}</title><style>${BASE_STYLES}</style></head>
  <body>
    <div class="no-print" style="margin-bottom: 20px;">
      <button onclick="window.print()" style="background:#0F172A;color:white;padding:10px 20px;border-radius:8px;font-weight:bold;border:none;cursor:pointer;">🖨️ Print / Save as PDF</button>
    </div>
    ${bodyHtml}
    <div class="footer">Generated by PathLearn Adaptive Learning Engine · ${escapeHtml(new Date().toLocaleString())}</div>
  </body>
</html>`);
    win.document.close();
  };
}

/** Numbered questions with blank workspace, grouped by section, plus an answer key on a new page. */
export function worksheetHtml(sections: { title: string; questions: PrintableQuestion[] }[]): string {
  let n = 0;
  const answers: string[] = [];
  const body = sections
    .map((section) => {
      const items = section.questions
        .map((q) => {
          n++;
          answers.push(
            `<tr><td>${n}</td><td>${String.fromCharCode(65 + q.answerIdx)}</td><td>${escapeHtml(
              q.options[q.answerIdx] ?? ""
            )}</td></tr>`
          );
          return `<div class="question">
            <strong>Q${n}.</strong> ${escapeHtml(q.text)}<span class="badge">Level ${q.difficulty}</span>
            <div class="options">${q.options
              .map((o, i) => `<div>(${String.fromCharCode(65 + i)}) ${escapeHtml(o)}</div>`)
              .join("")}</div>
            <div class="workspace"></div>
          </div>`;
        })
        .join("");
      return `<div class="section"><div class="section-title">${escapeHtml(section.title)}</div>${items}</div>`;
    })
    .join("");

  return `${body}
    <div class="answer-key">
      <div class="section-title">Answer Key (for the teacher)</div>
      <table><thead><tr><th>Q</th><th>Option</th><th>Answer</th></tr></thead><tbody>${answers.join("")}</tbody></table>
    </div>`;
}
