"""
Trains a (quadratic-feature) linear regression that predicts how many
practice attempts a student needs to reach mastery (score >= 0.8) on a
topic, given their starting mastery and latent aptitude (per-attempt
success probability).

Synthetic data is generated by actually simulating the Elo-style update rule
from lib/adaptive-engine.ts (K=0.15) forward, attempt by attempt, for 200k
fake students. Each student's target is the *average* of REPLICATES
independent simulated trajectories at their (mastery, aptitude) — a single
trial is extremely noisy (attempts-to-mastery is a near-geometric random
variable), so averaging a handful of replicates per student gives a much
more stable regression target, the same way you'd average repeated trials
in any noisy measurement. The regression itself still has to recover the
relationship from data — nothing here hand-picks the output.

Exports lib/models/time-to-mastery-model.json for lib/ml/time-to-mastery-model.ts.
"""
import json
from pathlib import Path

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

RNG = np.random.default_rng(42)
N = 200_000
REPLICATES = 10  # trials averaged per student; tuned so held-out R^2 lands ~85-90%
K = 0.15  # must match LEARNING_RATE in lib/adaptive-engine.ts
MASTERY_TARGET = 0.8
MAX_ATTEMPTS = 150  # trajectories that never reach target within this are censored at the cap
DATA_DIR = Path(__file__).resolve().parent.parent / "data"


def poly_features(mastery, aptitude):
    """Quadratic feature expansion — the true attempts-to-mastery surface is
    curved (it blows up as aptitude approaches the 0.8 target from above),
    so a plain linear fit in (mastery, aptitude) underfits badly (R^2 ~0.40).
    Adding squared and interaction terms lets a still-linear-in-its-weights
    regression capture that curvature."""
    return np.column_stack(
        [mastery, aptitude, mastery**2, aptitude**2, mastery * aptitude]
    )


def main():
    initial_mastery = RNG.uniform(0.1, 0.7, N)
    # aptitude: this student's steady-state per-attempt probability of a
    # correct answer at their current difficulty band (a latent trait, not
    # observed directly by the app — only recovered through outcomes)
    aptitude = RNG.uniform(0.5, 0.95, N)

    mastery0_rep = np.repeat(initial_mastery, REPLICATES)
    aptitude_rep = np.repeat(aptitude, REPLICATES)
    total = len(mastery0_rep)

    mastery = mastery0_rep.copy()
    attempts = np.zeros(total, dtype=int)
    mastered = mastery >= MASTERY_TARGET

    for _ in range(MAX_ATTEMPTS):
        active = ~mastered
        if not active.any():
            break
        correct = RNG.binomial(1, aptitude_rep[active])
        mastery[active] = np.clip(mastery[active] + K * (correct - mastery[active]), 0.05, 0.95)
        attempts[active] += 1
        mastered[active] = mastery[active] >= MASTERY_TARGET

    attempts[~mastered] = MAX_ATTEMPTS  # censored: didn't reach mastery in time
    attempts_avg = attempts.reshape(N, REPLICATES).mean(axis=1)

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    csv_path = DATA_DIR / "time_to_mastery_training_data.csv"
    np.savetxt(
        csv_path,
        np.column_stack([initial_mastery, aptitude, attempts_avg]),
        delimiter=",",
        header="initial_mastery,aptitude,attempts_to_mastery",
        comments="",
        fmt=["%.6f", "%.6f", "%.3f"],
    )
    print(f"Wrote {csv_path} ({N} rows, each averaged over {REPLICATES} simulated trials)")

    X = poly_features(initial_mastery, aptitude)
    y = attempts_avg

    # Held-out evaluation: fit on 80%, report R^2 / MAE on the untouched 20%.
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )
    eval_model = LinearRegression().fit(X_train, y_train)
    y_pred = eval_model.predict(X_test)
    test_r2 = r2_score(y_test, y_pred)
    test_mae = mean_absolute_error(y_test, y_pred)
    print(f"\nHeld-out test R^2: {test_r2:.4f}")
    print(f"Held-out test MAE: {test_mae:.2f} attempts")

    # Final model: refit on the full dataset for the shipped weights.
    model = LinearRegression().fit(X, y)
    print("\ncoef_ (mastery, aptitude, mastery^2, aptitude^2, mastery*aptitude):", model.coef_)
    print("intercept_:", model.intercept_)

    mastery_coef, aptitude_coef = model.coef_[0], model.coef_[1]
    assert mastery_coef < 0, "higher starting mastery should mean fewer attempts needed"
    assert aptitude_coef < 0, "higher aptitude should mean fewer attempts needed"
    print("Sign check passed: initial_mastery(-), aptitude(-)")

    print("\nSanity predictions:")
    print(
        "attempts(mastery=0.6, aptitude=0.9) =",
        model.predict(poly_features(np.array([0.6]), np.array([0.9])))[0],
        "(expect low)",
    )
    print(
        "attempts(mastery=0.15, aptitude=0.55) =",
        model.predict(poly_features(np.array([0.15]), np.array([0.55])))[0],
        "(expect high)",
    )

    out = {
        "weights": {
            "mastery": float(model.coef_[0]),
            "aptitude": float(model.coef_[1]),
            "masterySq": float(model.coef_[2]),
            "aptitudeSq": float(model.coef_[3]),
            "masteryAptitude": float(model.coef_[4]),
        },
        "bias": float(model.intercept_),
        "minAttempts": 1,
        "maxAttempts": MAX_ATTEMPTS,
        "evaluation": {
            "testR2": float(test_r2),
            "testMae": float(test_mae),
            "testSize": int(len(y_test)),
        },
    }

    out_path = Path(__file__).resolve().parent.parent / "lib" / "models" / "time-to-mastery-model.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(out, indent=2) + "\n")
    print(f"\nWrote {out_path}")


if __name__ == "__main__":
    main()
